feat: styled buttons
AdaptiveConsulting/early-careers-ui-kit-1 pull request #15
Opened 2023-01-19 15:55 UTC by adamshcao

2023-01-20 16:04 UTC, snony14 commented on components/src/button/Button.tsx
> +    if (buttonType === "secondary" && onLightBg) {
Is there an easier way to define all of these classes, many of the classes repeat.

2023-01-23 12:36 UTC, algreasley requested changes
Our end state should be more like this, with controls to toggle the state of the button
I know that is not clear from the ACs so this is not a criticism of this PR

![ui-kit-2022--button-with-controls](https://user-images.githubusercontent.com/8402485/214041050-551fd90d-332b-4c9f-a8ac-9f14b3ed353b.png)

2023-01-23 12:36 UTC, algreasley commented on components/src/button/Button.tsx
> +    }else if (buttonType === "secondary" && !onLightBg) {
could you sort out prettier in IDEA please .. I am going to make it a condition for approving this PR 😛

2023-01-23 12:36 UTC, algreasley commented on components/src/button/Button.tsx
> +    if (buttonType === "secondary" && onLightBg) {
yeah, does seem like a real ocean of classes .. I know that is, in general, "the tailwind way" but let's see if we can reduce the duplication ..

2023-01-24 14:32 UTC, tammyk7 approved these changes

2023-01-24 14:32 UTC, merged